name: Build Custom Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lock OpenSSL 1.1 (Block Action from Upgrading)
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg --force-all -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb libssl-dev_1.1.1f-1ubuntu2_amd64.deb
          sudo apt-mark hold libssl-dev libssl1.1

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          arch: arm64
          android-version: 14
          kernel-url: 'https://android.googlesource.com/kernel/common'
          kernel-branch: 'android14-6.1'
          config: gki_defconfig
          ksu: true
          nethunter: true
          nethunter-patch: false
